---
title: ""
toc: true 
link-external-newwindow: true
---

## Working Papers

**Private credit and Property prices: New insights into this nexus**</br> *with* <a href="https://sites.google.com/site/cesarruy"> Cesar Rodriguez </a>

<details>

<summary>Abstract</summary>

The relationship between the dynamics of property prices and private credit has long been a focal point for economists and policymakers, particularly given its role in financial stability. Understanding this relationship is especially crucial for developing economies, where financial markets are often less mature and more vulnerable to external shocks. This paper examines this relationship using quarterly data from 27 countries spanning 1982 to 2021. Through an instrumental variables approach that addresses endogeneity concerns, we identify three key findings. First, property price growth consistently drives private credit growth across both developed and developing economies, with a one percentage point increase in property prices associated with a 0.35 percentage point rise in private credit growth. Second, conventional macroeconomic factors such as interest rates, inflation, and GDP growth affect credit dynamics differently across development levels. Third, external factors, particularly trade openness and commodity price fluctuations, play an especially significant role in shaping credit dynamics in developing countries. Additionally, our analysis suggests that the property price-credit nexus has evolved, with notable shifts occurring around major economic events. Our results are robust to various sensitivity checks and alternative specifications and methodologies. These findings have important implications for the design of macroprudential policies, especially in developing economies where institutional capacities may differ from more developed markets.

</details>

Status: *Under Review at Journal of Real Estate Finance and Economics*

**To not move forward is to fall behind: Evidence of Policy Failure from India**</br>

<a href="https://oregonstate.box.com/s/ecnb0ngyq0awrtx296v61si9gdvyt5h4"> Summary </a>

<details>

<summary>Abstract</summary>

This paper studies the effect of non-implementation of education reforms on enrollment levels at the elementary school level in India. The paper exploits a unique natural experiment in which the Right of Children to Free and Compulsory Education (RTE) Act of 2009 was implemented in India, except for the state (now Union Territory(UT)) of Jammu \& Kashmir (J\&K). Using a quasi-experimental synthetic control approach, I estimate the causal impact of the non-implementation of the RTE act on enrollment levels in elementary schools in J\&K. Using household surveys and administrative data from the Ministry of Education, I find that on average nearly 300,000 (16.8\% more than pre-RTE enrollments) additional elementary-aged children could have enrolled annually if the act had been rolled out in J\&K. I demonstrate differential impacts of non-implementation of RTE across primary and upper primary levels of schooling and find that the negative effects are more pronounced at the upper primary level. I establish the economic significance through Mincer wage equations showing substantial lifetime earnings losses. I find that children in J\&K who complete elementary education earn 46\% more than children who do not.

</details>

Status: *Draft coming soon*

**The Reliability of Replications: A Study in Computational Reproductions** </br> *with* Nate Breznau et. al.

<a href="https://www.doi.org/10.31235/osf.io/j7qta"> Preprint </a>

<details>

<summary>Abstract</summary>

This paper reports findings from a crowdsourced replication. Eighty-five independent teams attempted a computational replication of results reported in an original study of policy preferences and immigration by fitting the same statistical models to the same data. The replication involved an experimental condition. Random assignment put participating teams into either the transparent group that received the original study and code, or the opaque group receiving only a methods section, rough results description and no code. The transparent group mostly verified the numerical results of the original study with the same sign and p-value threshold (95.7%), while the opaque group had less success (89.3%). Exact numerical reproductions to the second decimal place were far less common (76.9% and 48.1%), and the number of teams who verified at least 95% of all effects in all models they ran was 79.5% and 65.2% respectively. Therefore, the reliability we quantify depends on how reliability is defined, but most definitions suggest it would take a minimum of three independent replications to achieve reliability. Qualitative investigation of the teams’ workflows reveals many causes of error including mistakes and procedural variations. Although minor error across researchers is not surprising, we show this occurs where it is least expected in the case of computational reproduction. Even when we curate the results to boost ecological validity, the error remains large enough to undermine reliability between researchers to some extent. The presence of inter-researcher variability may explain some of the current “reliability crisis” in the social sciences because it may be undetected in all forms of research involving data analysis. The obvious implication of our study is more transparency. Broader implications are that researcher variability adds an additional meta-source of error that may not derive from conscious measurement or modeling decisions, and that replications cannot alone resolve this type of uncertainty.

</details>

Status: *Accepted Royal Society Open Science*

## Work-in-progress

**Improving school management in a low-income country: Experimental evidence from India** </br> *with* <a href="https://sites.google.com/site/toddpugatch/">Todd Pugatch</a> , <a href="http://ketkisheth.weebly.com">Ketki Sheth</a>, <a href="https://sites.google.com/view/nshakira-rukundo/home">Emmanuel Rukundo</a>

<details>

<summary>Abstract</summary>

... Coming soon

</details>

Status: *Data collection*

**Where morning feels different: Labor market consequences of state reorganisation in India**

<details>

<summary>Abstract</summary>

... Coming soon

</details>

Status: *Data Analysis*

**Connecting Communities, Reducing Conflict: Evidence from India's Rural Road Program**

<details>

<summary>Abstract</summary>

... Coming soon

</details>

Status: *Data Analysis*

**When Waters Recede: Impact of Extreme Weather Events on Child Labor**

<details>

<summary>Abstract</summary>

... Coming soon

</details>

Status: *Data cleaning*

**Learning or Earning: How Mandatory Education Shapes Child Labor in India**

<details>

<summary>Abstract</summary>

... Coming soon

</details>

Status: *Data cleaning*

**The Great (research) Divide: The long term dynamics of Coauthorship Networks in International Development**

<details>

<summary>Abstract</summary>

... Coming soon

</details>

Status: *Gathering data*

## Dormant Papers

**The Use of Behavioural-science Informed Interventions to Promote Latrine Use in Rural India: A Synthesis of Findings** </br>

*with* Charlotte Lane and Bethany Caruso

<a href="https://www.doi.org/10.31222/osf.io/g7cmd"> Preprint </a> <a href="https://doi.org/10.7910/DVN/IDJ8FJ"> Data and Code </a>\

**Making data accessible: lessons learned from computational reproducibility of impact evaluations** </br>

*with* Neeta Goel and Marie Gaarder

<a href="https://www.doi.org/10.31219/osf.io/4jvq2"> Preprint </a> <a href="https://doi.org/10.7910/DVN/FPNITS"> Data and Code </a>\
